package com.example.ammacias.quizzcofrade.localdb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ammacias.quizzcofrade.localdb.UsuarioDB;
import com.example.ammacias.quizzcofrade.localdb.HermandadDB;
import com.example.ammacias.quizzcofrade.localdb.PasosDB;
import com.example.ammacias.quizzcofrade.localdb.UsuariosHermandades;

import com.example.ammacias.quizzcofrade.localdb.UsuarioDBDao;
import com.example.ammacias.quizzcofrade.localdb.HermandadDBDao;
import com.example.ammacias.quizzcofrade.localdb.PasosDBDao;
import com.example.ammacias.quizzcofrade.localdb.UsuariosHermandadesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usuarioDBDaoConfig;
    private final DaoConfig hermandadDBDaoConfig;
    private final DaoConfig pasosDBDaoConfig;
    private final DaoConfig usuariosHermandadesDaoConfig;

    private final UsuarioDBDao usuarioDBDao;
    private final HermandadDBDao hermandadDBDao;
    private final PasosDBDao pasosDBDao;
    private final UsuariosHermandadesDao usuariosHermandadesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usuarioDBDaoConfig = daoConfigMap.get(UsuarioDBDao.class).clone();
        usuarioDBDaoConfig.initIdentityScope(type);

        hermandadDBDaoConfig = daoConfigMap.get(HermandadDBDao.class).clone();
        hermandadDBDaoConfig.initIdentityScope(type);

        pasosDBDaoConfig = daoConfigMap.get(PasosDBDao.class).clone();
        pasosDBDaoConfig.initIdentityScope(type);

        usuariosHermandadesDaoConfig = daoConfigMap.get(UsuariosHermandadesDao.class).clone();
        usuariosHermandadesDaoConfig.initIdentityScope(type);

        usuarioDBDao = new UsuarioDBDao(usuarioDBDaoConfig, this);
        hermandadDBDao = new HermandadDBDao(hermandadDBDaoConfig, this);
        pasosDBDao = new PasosDBDao(pasosDBDaoConfig, this);
        usuariosHermandadesDao = new UsuariosHermandadesDao(usuariosHermandadesDaoConfig, this);

        registerDao(UsuarioDB.class, usuarioDBDao);
        registerDao(HermandadDB.class, hermandadDBDao);
        registerDao(PasosDB.class, pasosDBDao);
        registerDao(UsuariosHermandades.class, usuariosHermandadesDao);
    }
    
    public void clear() {
        usuarioDBDaoConfig.getIdentityScope().clear();
        hermandadDBDaoConfig.getIdentityScope().clear();
        pasosDBDaoConfig.getIdentityScope().clear();
        usuariosHermandadesDaoConfig.getIdentityScope().clear();
    }

    public UsuarioDBDao getUsuarioDBDao() {
        return usuarioDBDao;
    }

    public HermandadDBDao getHermandadDBDao() {
        return hermandadDBDao;
    }

    public PasosDBDao getPasosDBDao() {
        return pasosDBDao;
    }

    public UsuariosHermandadesDao getUsuariosHermandadesDao() {
        return usuariosHermandadesDao;
    }

}
