package com.example.ammacias.quizzcofrade.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HERMANDAD_DBT".
 */
@Entity
public class HermandadDBT {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombre;

    @NotNull
    private String escudo;

    @NotNull
    private String tunica;

    @NotNull
    private String fotoTunica;

    @NotNull
    private String dia;
    private int numNazarenos;

    @NotNull
    private String anyoFundacion;

    @Generated
    public HermandadDBT() {
    }

    public HermandadDBT(Long id) {
        this.id = id;
    }

    @Generated
    public HermandadDBT(Long id, String nombre, String escudo, String tunica, String fotoTunica, String dia, int numNazarenos, String anyoFundacion) {
        this.id = id;
        this.nombre = nombre;
        this.escudo = escudo;
        this.tunica = tunica;
        this.fotoTunica = fotoTunica;
        this.dia = dia;
        this.numNazarenos = numNazarenos;
        this.anyoFundacion = anyoFundacion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(@NotNull String nombre) {
        this.nombre = nombre;
    }

    @NotNull
    public String getEscudo() {
        return escudo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEscudo(@NotNull String escudo) {
        this.escudo = escudo;
    }

    @NotNull
    public String getTunica() {
        return tunica;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTunica(@NotNull String tunica) {
        this.tunica = tunica;
    }

    @NotNull
    public String getFotoTunica() {
        return fotoTunica;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFotoTunica(@NotNull String fotoTunica) {
        this.fotoTunica = fotoTunica;
    }

    @NotNull
    public String getDia() {
        return dia;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDia(@NotNull String dia) {
        this.dia = dia;
    }

    public int getNumNazarenos() {
        return numNazarenos;
    }

    public void setNumNazarenos(int numNazarenos) {
        this.numNazarenos = numNazarenos;
    }

    @NotNull
    public String getAnyoFundacion() {
        return anyoFundacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnyoFundacion(@NotNull String anyoFundacion) {
        this.anyoFundacion = anyoFundacion;
    }

    @Override
    public String toString() {
        return "HermandadDBT{" +
                "nombre='" + nombre + '\'' +
                '}';
    }
}
