package com.example.ammacias.quizzcofrade.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MARCHA_DB".
 */
@Entity
public class MarchaDB {

    @Id(autoincrement = true)
    private Long id;
    private String nombre;
    private String banda;
    private String fecha;
    private String ruta;

    @Generated
    public MarchaDB() {
    }

    public MarchaDB(Long id) {
        this.id = id;
    }

    @Generated
    public MarchaDB(Long id, String nombre, String banda, String fecha, String ruta) {
        this.id = id;
        this.nombre = nombre;
        this.banda = banda;
        this.fecha = fecha;
        this.ruta = ruta;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getBanda() {
        return banda;
    }

    public void setBanda(String banda) {
        this.banda = banda;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

}
