package com.example.ammacias.quizzcofrade.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PASOS_DB".
 */
@Entity
public class PasosDB {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String nombreTitular;

    @NotNull
    private String foto;

    @NotNull
    private String banda;
    private long idHermandad;

    @Generated
    public PasosDB() {
    }

    public PasosDB(Long id) {
        this.id = id;
    }

    @Generated
    public PasosDB(Long id, String nombreTitular, String foto, String banda, long idHermandad) {
        this.id = id;
        this.nombreTitular = nombreTitular;
        this.foto = foto;
        this.banda = banda;
        this.idHermandad = idHermandad;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNombreTitular() {
        return nombreTitular;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombreTitular(@NotNull String nombreTitular) {
        this.nombreTitular = nombreTitular;
    }

    @NotNull
    public String getFoto() {
        return foto;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFoto(@NotNull String foto) {
        this.foto = foto;
    }

    @NotNull
    public String getBanda() {
        return banda;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBanda(@NotNull String banda) {
        this.banda = banda;
    }

    public long getIdHermandad() {
        return idHermandad;
    }

    public void setIdHermandad(long idHermandad) {
        this.idHermandad = idHermandad;
    }

}
