package com.example.ammacias.quizzcofrade.localdb;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PASOS_DB".
*/
public class PasosDBDao extends AbstractDao<PasosDB, Long> {

    public static final String TABLENAME = "PASOS_DB";

    /**
     * Properties of entity PasosDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdHermandad = new Property(1, long.class, "idHermandad", false, "ID_HERMANDAD");
        public final static Property NombreTitular = new Property(2, String.class, "nombreTitular", false, "NOMBRE_TITULAR");
        public final static Property Foto = new Property(3, String.class, "foto", false, "FOTO");
        public final static Property ColorCirio = new Property(4, String.class, "colorCirio", false, "COLOR_CIRIO");
        public final static Property Banda = new Property(5, String.class, "banda", false, "BANDA");
        public final static Property Capataz = new Property(6, String.class, "capataz", false, "CAPATAZ");
        public final static Property NumCostaleros = new Property(7, String.class, "numCostaleros", false, "NUM_COSTALEROS");
        public final static Property Llamador = new Property(8, String.class, "llamador", false, "LLAMADOR");
    };


    public PasosDBDao(DaoConfig config) {
        super(config);
    }
    
    public PasosDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PASOS_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ID_HERMANDAD\" INTEGER NOT NULL ," + // 1: idHermandad
                "\"NOMBRE_TITULAR\" TEXT NOT NULL ," + // 2: nombreTitular
                "\"FOTO\" TEXT NOT NULL ," + // 3: foto
                "\"COLOR_CIRIO\" TEXT NOT NULL ," + // 4: colorCirio
                "\"BANDA\" TEXT NOT NULL ," + // 5: banda
                "\"CAPATAZ\" TEXT NOT NULL ," + // 6: capataz
                "\"NUM_COSTALEROS\" TEXT NOT NULL ," + // 7: numCostaleros
                "\"LLAMADOR\" TEXT NOT NULL );"); // 8: llamador
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PASOS_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PasosDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdHermandad());
        stmt.bindString(3, entity.getNombreTitular());
        stmt.bindString(4, entity.getFoto());
        stmt.bindString(5, entity.getColorCirio());
        stmt.bindString(6, entity.getBanda());
        stmt.bindString(7, entity.getCapataz());
        stmt.bindString(8, entity.getNumCostaleros());
        stmt.bindString(9, entity.getLlamador());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PasosDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdHermandad());
        stmt.bindString(3, entity.getNombreTitular());
        stmt.bindString(4, entity.getFoto());
        stmt.bindString(5, entity.getColorCirio());
        stmt.bindString(6, entity.getBanda());
        stmt.bindString(7, entity.getCapataz());
        stmt.bindString(8, entity.getNumCostaleros());
        stmt.bindString(9, entity.getLlamador());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PasosDB readEntity(Cursor cursor, int offset) {
        PasosDB entity = new PasosDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // idHermandad
            cursor.getString(offset + 2), // nombreTitular
            cursor.getString(offset + 3), // foto
            cursor.getString(offset + 4), // colorCirio
            cursor.getString(offset + 5), // banda
            cursor.getString(offset + 6), // capataz
            cursor.getString(offset + 7), // numCostaleros
            cursor.getString(offset + 8) // llamador
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PasosDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdHermandad(cursor.getLong(offset + 1));
        entity.setNombreTitular(cursor.getString(offset + 2));
        entity.setFoto(cursor.getString(offset + 3));
        entity.setColorCirio(cursor.getString(offset + 4));
        entity.setBanda(cursor.getString(offset + 5));
        entity.setCapataz(cursor.getString(offset + 6));
        entity.setNumCostaleros(cursor.getString(offset + 7));
        entity.setLlamador(cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PasosDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PasosDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
