package com.example.ammacias.quizzcofrade.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USUARIOS_HERMANDADES_DB".
 */
@Entity
public class UsuariosHermandadesDB {

    @Id(autoincrement = true)
    private Long id;
    private long idUsuario;
    private long idHermandad;

    @NotNull
    private String categoria;

    @Generated
    public UsuariosHermandadesDB() {
    }

    public UsuariosHermandadesDB(Long id) {
        this.id = id;
    }

    @Generated
    public UsuariosHermandadesDB(Long id, long idUsuario, long idHermandad, String categoria) {
        this.id = id;
        this.idUsuario = idUsuario;
        this.idHermandad = idHermandad;
        this.categoria = categoria;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public long getIdHermandad() {
        return idHermandad;
    }

    public void setIdHermandad(long idHermandad) {
        this.idHermandad = idHermandad;
    }

    @NotNull
    public String getCategoria() {
        return categoria;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoria(@NotNull String categoria) {
        this.categoria = categoria;
    }

    @Override
    public String toString() {
        return "UsuariosHermandadesDB{" +
                "id=" + id +
                ", idUsuario=" + idUsuario +
                ", idHermandad=" + idHermandad +
                ", categoria='" + categoria + '\'' +
                '}';
    }
}
