package com.gabantdev.quizzcofrade.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RANKING_DB".
 */
@Entity
public class RankingDB {

    @Id(autoincrement = true)
    private Long id;
    private Long idUsuario;
    private String nombre;
    private String apellidos;
    private String idface;
    private Integer aciertos;
    private String fecha;

    @Generated
    public RankingDB() {
    }

    public RankingDB(Long id) {
        this.id = id;
    }

    @Generated
    public RankingDB(Long id, Long idUsuario, String nombre, String apellidos, String idface, Integer aciertos, String fecha) {
        this.id = id;
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.idface = idface;
        this.aciertos = aciertos;
        this.fecha = fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getIdface() {
        return idface;
    }

    public void setIdface(String idface) {
        this.idface = idface;
    }

    public Integer getAciertos() {
        return aciertos;
    }

    public void setAciertos(Integer aciertos) {
        this.aciertos = aciertos;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

}
